name: Publish Frontend to Azure

on:
  workflow_dispatch:
  push:
    branches:
      - release

env:
  AZURE_WEBAPP_NAME: digital-twins-kpi-ui
  AZURE_WEBAPP_PACKAGE_PATH: './client/build'
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
        
    - name: Setup Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: 'Install dependencies, build'
      run: |
          yarn install --frozen-lockfile
          yarn build
      working-directory: ./client

    - name: Deploy application
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_UI }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
